# Generated by Django 5.0.6 on 2024-06-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sembol', models.CharField(blank=True, max_length=10)),
                ('isim', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
